### ISSUE TITLE
/query/last returns empty data

### ISSUE THREAD

**Issue by mgoralczyk-viasat** [OpenTSDB/opentsdb#691]
After upgrading from 2.1.0 to 2.2.0RC3 I have noticed issues with the /query/last endpoint. I get empty returns even though there is data.

For example, say I create some data like so:
`put metatest 1454339442 1 foo=1 bar=1`
`put metatest 1454339443 2 foo=1 bar=2`
`put metatest 1454339444 3 foo=1 bar=3`
`put metatest 1454339445 4 foo=1 bar=4`
`put metatest 1454339446 5 foo=1 bar=5`

If I then call any of the following combinations of the /query/last endpoint I get empty returns ("[]"):
`http://localhost:4242/api/query/last?timeseries=metatest{foo=1,bar=1}`
`http://localhost:4242/api/query/last?timeseries=metatest{foo=1}`
`http://localhost:4242/api/query/last?timeseries=metatest{bar=1}`
`http://localhost:4242/api/query/last?timeseries=metatest`

It also seems that wildcards are not supported by this endpoint. If that is true, could I make a feature request? 
`http://localhost:4242/api/query/last?timeseries=metatest{foo=1,bar=*}`

I've enabled all metadata to be sure it wasn't a config issue. I don't use backscan because I have tag values that change often (roughly daily) and are non-deterministic. 
`tsd.core.meta.enable_realtime_uid = true`
`tsd.core.meta.enable_realtime_ts = true`
`tsd.core.meta.enable_tsuid_incrementing = true`
`tsd.core.meta.enable_tsuid_tracking = true`

As a note, I have this issue on HBase 1.0.0 and 1.0.2. 

Thanks in advance,
-Matt

**Comment by manolama** [comment]
Fixed in d9347e55aba4b6a261898374932b0f0664771a5f, thanks!

**Comment by mgoralczyk-viasat** [comment]
Since I'm too familiar yet, will this fix be in 2.2 stable when it comes out?

Thanks!

**Comment by andrejserafim** [comment]
@mgoralczyk-viasat looks like this is still an issue in 2.2, I can get `/query/last` to return values if the time is within 24hrs (no backScan), but not further than that. I have some luck when using tsuids (as opposed to metrics and tags) and backScan, but only upto like 1000hrs.

**Comment by markmnl** [comment]
Still an issue in 2.3
